### ISSUE TITLE
Little document mistype

### ISSUE THREAD

**Issue by jdgcs** [aeternity/epoch#1120]
https://github.com/aeternity/epoch/blob/master/docs/operation.md

## Expected Behavior
With the Minimal testnet config, two curl http://127.0.0.1:3003/v2/top should be:

curl http://127.0.0.1:3013/v2/top

...

## Actual Behavior
curl http://127.0.0.1:3003/v2/top

**Comment by dincho** [comment]
Docs ports has been reconsidered in 8fb5d3b4a39415f3c7aeb054f9ce9c9e3cc36df4 and ec95eb566c75a6818ff6a645f532173401fea6df.

Should be fine now.
