### ISSUE TITLE
Land websockets for the secure internal interface

### ISSUE THREAD

**Issue by wagerlabs** [aeternity/epoch#117]
Implement websockets for the internal interface. This is a secure interface bound to the local IP address, that allows full management of the node.

- Accept more than a single connection since multiple aepps may be running locally.
- Define the JSON format for the requests and responses, as well as node events.
- Push out events like completion of mining, award of a block reward, etc. 

N.B. We'll add more events as time goes by.

**Comment by uwiger** [comment]
PR #125 introduces aehttp, using cowboy, which is websocket-capable...

**Comment by wagerlabs** [comment]
https://www.pivotaltracker.com/story/show/152480644
