### ISSUE TITLE
Can not download v-0.15.0

### ISSUE THREAD

**Issue by tc2096** [aeternity/epoch#1231]
## Expected Behavior

...I Cannot download it

## Actual Behavior

...

## Steps to Reproduce the Problem

  1. ...
  1. ...
  1. ...
  
  
## Logs, error output, etc.
 
 (`epoch.yaml` configuration file, `log/epoch.log` log file plus other related logs, e.g., `log/epoch_sync.log`, `log/epoch_mining.log`; if it’s long, please paste to https://ghostbin.com/ and insert the link here)
 
 ...

## Specifications

  - Virtualization: [*none / metal / container / VM*]
  - Hardware specs: 
    * RAM: 
    * CPU:
  - OS: [*distribution, version*]
  - Node Version:

**Comment by dincho** [comment]
@tc2096 Can you be more specific and fill in the "Steps to Reproduce the Problem" section of the issue? It's in the issue template on purpose.

**Comment by evdoks** [comment]
Closing as stale.
