### ISSUE TITLE
Deterministic hashing

### ISSUE THREAD

**Issue by wagerlabs** [aeternity/epoch#124]
We need to be able to reproduce the hashes on all sorts of platforms so the logic needs to be predictable, e.g.

- Serialize everything into a byte array.
- Store integers as little-endian.

We'll serialize structures field by field into a byte buffer and then hash that.

**Comment by wagerlabs** [comment]
We'll need to switch away from using `term_to_binary` as part of implementing this ticket.

**Comment by akorosmezey** [comment]
Field definitions: https://github.com/aeternity/epoch/wiki/Block-Header

**Comment by sennui** [comment]
This will be ongoing on all platforms, closing for now as main requirement is implemented (term_to_binary replaced by json)
