### ISSUE TITLE
Mining RPC, stratum spec, standalone miner in C

### ISSUE THREAD

**Issue by sammy007** [aeternity/epoch#1253]
This part must be addressed prior launch imo. With ofc stratum spec and a standalone CPU miner which can act like a reference client to it the mining ecosystem will be consistent since genesis block. If you ignore it AE will end up with tons of closed source taxable miners and affiliated pools.

* Document RPC endpoints responsible for jobs
* Develop a stratum protocol specification
* Develop a reference client for this stratum

ETH launch: many stratum modes, almost 100% proprietary mining software with dev tax.
ZCash launch: consistent stratums due to spec ready prior launch, 100% proprietary mining software with dev tax.

**Comment by sammy007** [comment]
No idea how AE PoW works, but I am guessing it's still hashing. The ZCash stratum spec could be a good start https://github.com/str4d/zips/blob/77-zip-stratum/drafts/str4d-stratum/draft1.rst

**Comment by sammy007** [comment]
Is it currently possible to get data required for stratum from a node just like a `getwork` in ETH?

**Comment by knarz** [comment]
`getWork` and `submitWork` should be implemented in the next sprint but they will work pretty much like the Ethereum methods.

**Comment by sammy007** [comment]
> pretty much like the Ethereum methods.

The `eth_getWork` for years was a big pita due to lack of block height in response and required 2 RPC call to get height and work separately, the result was inconsistent and caused additional pita to search for a block (including uncles) in a pretty weird way. Later parity client added 4th param in response to return a block height. I hope you guys will address this issue as well.
