### ISSUE TITLE
Default keys path

### ISSUE THREAD

**Issue by cytadela8** [aeternity/epoch#126]
We have the following line in `/apps/aecore/aec_keys.erl':
```
KeysDir = application:get_env(aecore, keys_dir, filename:join(code:root_dir(), "keys")),
```

We default to `code:root_dir()` = Erlang instalation path for the path for keys. That's not good, because most probably it's not writable. (eg. `/usr/local/otp`)

We should change the path to something else. For example: an folder in user home dir or current working directory.

Current behaviour creates problems when trying to run tests. Unless your Erlang is installed in a folder writeable by current user (common when you compile Erlang yourself), `aec_keys` tests will fail.

**Comment by cytadela8** [comment]
@sennui

**Comment by sennui** [comment]
@cytadela8 interesting. I wonder why it kicks in, given that we have default /tmp:

https://github.com/aeternity/epoch/blob/master/config/sys.config#L7

**Comment by cytadela8** [comment]
I think it was said yesterday that in tests there are no environment variables?

**Comment by sennui** [comment]
@cytadela8 true, indeed!

So, all clear, it fails because it may happen that we do not have access to a dir.

I just wonder why we didn't see a badmatch crash

**Comment by dincho** [comment]
I believe this is already resolved and keys dir is automatically created, and keys test are passing.
