### ISSUE TITLE
would ae provide an api to get all transactions history of a specific account ?

### ISSUE THREAD

**Issue by jayphbee** [aeternity/epoch#1321]

**Comment by jayphbee** [comment]
Ethereum would never add such an api, as this [issue](https://github.com/ethereum/go-ethereum/issues/1897) debated. I think this api is friendly for developers, would like to know if ae could support this api?

**Comment by gorillainduction** [comment]
We have been discussing this kind of indexing for quite some time, and this week we decided that we will make such indexing optionally available to nodes.

This is tracked by the ticket https://www.pivotaltracker.com/n/projects/2124891/stories/158816256

**Comment by jayphbee** [comment]
Could you give me a hint how do you make this kind of indexing fast and space efficient?

**Comment by evdoks** [comment]
Closing as answered.
