### ISSUE TITLE
Setup release packaging

### ISSUE THREAD

**Issue by wagerlabs** [aeternity/epoch#157]

**Comment by lucafavatella** [comment]
Objectives:
* [ ] OTP release, including Erlang VM, built for Ubuntu by Travis and uploaded by Travis to GitHub on git tag;
* [ ] OTP release, including Erlang VM, built for OSX by Travis and uploaded by Travis to GitHub on git tag.

The exact Ubuntu and OSX architecture and version I will build for will be constrained by what Travis offers i.e. I do not plan to perform cross-compilation.

----

An alternative - or complement - would have been to have a Docker container. But Docker image seems less simple - both to use and to build. So I plan not to target Docker. (Of course the Ubuntu package may be used for building Docker image, but I consider that out of scope.)

Cc @wagerlabs @sennui

**Comment by lucafavatella** [comment]
This is a tag on master https://github.com/aeternity/epoch/releases/tag/tag-007f40a
on which Travis shall eventually upload the packages (Ubuntu, new OSX, old OSX).

**Comment by wagerlabs** [comment]
A new tag needs to be created which will trigger Travis build and the artifacts will appear under the tag.
