### ISSUE TITLE
Epoch keeps crashing

### ISSUE THREAD

**Issue by baltar** [aeternity/epoch#1594]
## Expected Behavior

Start mining

## Actual Behavior

Keeps crashing

## Steps to Reproduce the Problem

  1. Download MacOS node 0.22.0 from 
https://github.com/aeternity/epoch/releases/download/v0.22.0/epoch-0.22.0-osx-10.12.6.tar.gz
  1. Follow installation + configuration + operation instructions from doc directory.
  
  
## Logs, error output, etc.
 
tail of log/crash.log:

`2018-09-26 14:43:37 =CRASH REPORT====
  crasher:
    initial call: jobs:run/2
    pid: <0.4364.0>
    registered_name: []
    exception exit: {{{badarg,[{enacl_nif,crypto_aead_chacha20poly1305_decrypt,[<<32,122,103,195,44,21,129,231,69,226,82,62,154,194,162,140,61,136,170,252,76,182,191,190,193,186,222,134,236,175,136,253>>,<<0,0,0,0,7,0,0,0,0,0,0,0>>,<<>>,<<"Y»Ce­">>],[]},{enoise_cipher_state,decrypt_with_ad,3,[{file,"/Users/distiller/epoch/_build/default/lib/enoise/src/enoise_cipher_state.erl"},{line,64}]},{enoise_connection,handle_data,2,[{file,"/Users/distiller/epoch/_build/default/lib/enoise/src/enoise_connection.erl"},{line,150}]},{enoise_connection,handle_info,2,[{file,"/Users/distiller/epoch/_build/default/lib/enoise/src/enoise_connection.erl"},{line,92}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,616}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,686}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]},{gen_server,call,[<0.4328.0>,{get_generation,[<<109,114,106,111,0,206,184,168,199,115,89,40,243,6,148,169,43,191,15,220,56,192,8,142,84,34,127,68,164,178,22,223>>,backward]},7000]}},[{gen_server,call,3,[{file,"gen_server.erl"},{line,214}]},{aec_peer_connection,call,2,[{file,"/Users/distiller/epoch/_build/prod/lib/aecore/src/aec_peer_connection.erl"},{line,120}]},{aec_sync,do_fetch_generation_ext,2,[{file,"/Users/distiller/epoch/_build/prod/lib/aecore/src/aec_sync.erl"},{line,761}]},{aec_sync,do_work_on_sync_task,3,[{file,"/Users/distiller/epoch/_build/prod/lib/aecore/src/aec_sync.erl"},{line,654}]},{jobs_server,run,2,[{file,"/Users/distiller/epoch/_build/default/lib/jobs/src/jobs_server.erl"},{line,107}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
    ancestors: [aec_sync,aec_connection_sup,aecore_sup,<0.1189.0>]
    message_queue_len: 0
    messages: []
    links: [<0.1237.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 4185
    stack_size: 27
    reductions: 30427
  neighbours:
2018-09-26 14:43:37 =SUPERVISOR REPORT====
     Supervisor: {local,aec_peer_connection_sup}
     Context:    child_terminated
     Reason:     {badarg,[{enacl_nif,crypto_aead_chacha20poly1305_decrypt,[<<32,122,103,195,44,21,129,231,69,226,82,62,154,194,162,140,61,136,170,252,76,182,191,190,193,186,222,134,236,175,136,253>>,<<0,0,0,0,7,0,0,0,0,0,0,0>>,<<>>,<<"Y»Ce­">>],[]},{enoise_cipher_state,decrypt_with_ad,3,[{file,"/Users/distiller/epoch/_build/default/lib/enoise/src/enoise_cipher_state.erl"},{line,64}]},{enoise_connection,handle_data,2,[{file,"/Users/distiller/epoch/_build/default/lib/enoise/src/enoise_connection.erl"},{line,150}]},{enoise_connection,handle_info,2,[{file,"/Users/distiller/epoch/_build/default/lib/enoise/src/enoise_connection.erl"},{line,92}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,616}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,686}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
     Offender:   [{pid,<0.4328.0>},{id,aec_peer_connection},{mfargs,{aec_peer_connection,connect_start_link,undefined}},{restart_type,temporary},{shutdown,5000},{child_type,worker}]`

tail of log/epoch.log:

`2018-09-26 14:47:03.807 [error] <0.7400.0>@enoise_cipher_state:decrypt_with_ad:64 CRASH REPORT Process <0.7400.0> with 1 neighbours crashed with reason: bad argument in call to enacl_nif:crypto_aead_chacha20poly1305_decrypt(<<102,63,126,73,223,171,80,123,105,128,233,11,89,58,121,248,156,37,249,118,209,180,220,99,19,202,...>>, <<0,0,0,0,12,0,0,0,0,0,0,0>>, <<>>, <<158,178,34,221,162>>) in enoise_cipher_state:decrypt_with_ad/3 line 64
2018-09-26 14:47:03.807 [error] <0.1234.0>@enoise_cipher_state:decrypt_with_ad:64 Supervisor aec_peer_connection_sup had child aec_peer_connection started with {aec_peer_connection,connect_start_link,undefined} at <0.7394.0> exit with reason bad argument in call to enacl_nif:crypto_aead_chacha20poly1305_decrypt(<<102,63,126,73,223,171,80,123,105,128,233,11,89,58,121,248,156,37,249,118,209,180,220,99,19,202,...>>, <<0,0,0,0,12,0,0,0,0,0,0,0>>, <<>>, <<158,178,34,221,162>>) in enoise_cipher_state:decrypt_with_ad/3 line 64 in context child_terminated
2018-09-26 14:47:03.807 [error] <0.7420.0>@enoise_cipher_state:decrypt_with_ad:64 CRASH REPORT Process <0.7420.0> with 0 neighbours exited with reason: bad argument in call to enacl_nif:crypto_aead_chacha20poly1305_decrypt(<<102,63,126,73,223,171,80,123,105,128,233,11,89,58,121,248,156,37,249,118,209,180,220,99,19,202,...>>, <<0,0,0,0,12,0,0,0,0,0,0,0>>, <<>>, <<158,178,34,221,162>>) in enoise_cipher_state:decrypt_with_ad/3 line 64 in gen_server:call/3 line 214
`

## Specifications

  - Virtualization: none
  - Hardware specs: 
    * RAM: 16GB
    * CPU: 2.9 GHz Intel Core i7
  - OS: MacOS 
  - Node Version: 0.22.0

**Comment by dincho** [comment]
@baltar This is known issue that is already fixed in master, we release 0.23.0 tomorrow including the fix.

**Comment by baltar** [comment]
I now tested this again with v0.23.0 and it worked.
