### ISSUE TITLE
Possible bugs in Map method application error reporting.

### ISSUE THREAD

**Issue by baltar** [aeternity/epoch#1627]
Not sure if this is supposed to be like this, but in https://github.com/aeternity/epoch/blob/master/apps/aesophia/src/aeso_ast_to_icode.erl lines 266-268:
```
ast_body({qid, _, ["Map", "to_list"]}, _Icode)   -> error({underapplied_primitive, 'Map.to_list'});
ast_body({qid, _, ["Map", "lookup"]}, _Icode)    -> error({underapplied_primitive, 'Map.to_list'});
ast_body({qid, _, ["Map", "member"]}, _Icode)    -> error({underapplied_primitive, 'Map.to_list'});
```
Should the last 2 `'Map.to_list'` not be `'Map.lookup'` and `'Map.member'`, respectively?

**Comment by hanssv** [comment]
Yes, looks wrong. It is already fixed in https://github.com/aeternity/epoch/commit/7c39535b21d8856d629f870a053582f23c92657c
