### ISSUE TITLE
Wrong docker image identifier.

### ISSUE THREAD

**Issue by filipdujmusic** [aeternity/epoch#1635]
Wrong docker image identifier in more than one place. (for example [here](https://github.com/aeternity/epoch/blob/v0.9.0/docs/docker.md)).

It should be **aeternity/epoch**. Links to Docker Hub should also be corrected.

**Comment by hanssv** [comment]
That is the documentation for version 0.9.0, at that time that was the correct docker image identifier. 

Current version is 0.23.0 and there the identifiers seems to be the correct ones.
