### ISSUE TITLE
How to get AE Address

### ISSUE THREAD

**Issue by kryztoval** [aeternity/epoch#1692]
## Expected Behavior
Says you can get your address using 
 curl http://127.0.0.1:3113/v2/account/pub-key
...

## Actual Behavior
I get a 404
...

## Steps to Reproduce the Problem

  1. Install verison 0.24
  2. Try it it fails.
  
  
## Logs, error output, etc.
 
:~/node$ curl http://127.0.0.1:3113/v2/account/pub-key -vvv
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 3113 (#0)
> GET /v2/account/pub-key HTTP/1.1
> Host: 127.0.0.1:3113
> User-Agent: curl/7.58.0
> Accept: */*
>
< HTTP/1.1 404 Not Found
< content-length: 0
< date: Thu, 25 Oct 2018 09:33:15 GMT
< server: Cowboy
<
* Connection #0 to host 127.0.0.1 left intact

## Specifications

Virtualization: version 18.06.1-ce, build e68fc7a
Hardware specs:
RAM: 4gb
CPU: 2.4GHz 2xCores
OS: Centos 7
Node Version: aeternity/epoch:latest (36c969d29950) 0.24

**Comment by kryztoval** [comment]
How to get ae address #1228 was used as reference for how to get the address

**Comment by d-velev** [comment]
https://github.com/aeternity/protocol/blob/master/epoch/api/account_api_usage.md#retrieve-your-public-key

**Comment by kryztoval** [comment]
@d-velev Thanks for that reference

So now you get your account with:
curl http://127.0.0.1:3113/v2/debug/accounts/node

Thanks, I think this means the documentation needs to be updated, for the tutorial part at least, since the ones available and linked in aeternity still show the old version and the old links.

**Comment by kryztoval** [comment]
Those are the first resulfs for the basic google search as to how to get your balance or get your public key
https://github.com/aeternity/epoch/wiki/HTTP-Client-API:-get-account-balance
https://github.com/aeternity/epoch/issues/1228
 This last one refers to this one
https://github.com/aeternity/protocol/blob/epoch-v0.15.0/epoch/api/account_api_usage.md#retrieve-your-public-key
