### ISSUE TITLE
epoch keys_gen error: undefined function crypto:hash/2

### ISSUE THREAD

**Issue by cauu** [aeternity/epoch#1707]
## Behaviour
I follow the [Tutorial: Mining AE on Ubuntu 18.04](https://blog.aeternity.com/tutorial-mining-ae-on-ubuntu-18-04-f4d1f908b0fd), after finish the installation of all dependencies, I run `./epoch keys_gen PASSWORD`, but it reports `escript: exception error: undefined function crypto:hash/2`.

## Specifications
docker image: ubuntu:18.04

**Comment by kryztoval** [comment]
I see you said docker image ubuntu 18.04

Are you following the standard installation on an ubuntu docker image?
Wouldn't it be easier to use the official docker image instead?

**Comment by dincho** [comment]
As @kryztoval suggested it would be easier to run our docker image indeed (it's alpine linux however).

However, if you prefer to follow the tutorial and run the node on ubuntu 18.04, I think you need to install [older libssl version](https://github.com/aeternity/epoch/blob/master/docs/installation.md#ubuntu-1804): `sudo apt-get install libssl1.0.0`

Not sure why we're missing that in the tutorial, I'll make sure it's updated.

**Comment by Zwilla** [comment]
I think the problem is outdated, because we are on a higher release now.
But it would be great if someone of you update the obsolete tutorial above.

**Comment by evdoks** [comment]
@Zwilla We've updated the guide. Thanks for noticing.
