### ISSUE TITLE
Remove the ulimit mandatory setting

### ISSUE THREAD

**Issue by sammy007** [aeternity/epoch#1761]
Seriously do you think it's a great idea to require 25K open files limit? Okay, there is tons of OSX versions and it seems you have to spend a day figuring it out how to adjust this ulimit settings, it's just a no go. I can't believe that it's impossible to run this p2p client on a default system. If I can run the ethereum snake oil on a laptop with default settings I am sure I can run this one as well. Please remove open files limit, let it fail already if not enough.

ps: Please stop jerking with a technology rewriting it on 2 languages for the same VM which is like writing a soft on both VB.net and C# without any reason just to pleasure yourself.

**Comment by Zwilla** [comment]
have the same issue on ubuntu every time I reboot and want to restart. I get the error message but the node starts normal (have a fixed of 1000)

**Comment by sammy007** [comment]
You can configure ubuntu in 5 minutes:

/etc/security/limits.d/epoch.conf

```
<username> soft nofile 512000
<username> hard nofile 512000
```

Replace `<username>` with a user under which you are running epoch. Then re-login or reboot. If you are using systemd you must look for systemd config params`LimitNOFILE=65536`.

The OSX issue is that nobody is familiar with their extremely convoluted configs and it's literally a pita to find any correct documentation.

**Comment by Zwilla** [comment]
Great! Confirm this solution works!
But I will mark this issue as unsolved as long the team have edited the docs.

**Comment by evdoks** [comment]
Tracked as Pivotal Tracker [ticket](https://www.pivotaltracker.com/story/show/162156314).
