### ISSUE TITLE
Inconsistent packaging

### ISSUE THREAD

**Issue by sammy007** [aeternity/epoch#1762]
OSX release unpacks to `epoch-0.25.0-osx-10.12.6`. Linux release unpacks to the current directory polluting it. Must unpack to `epoch-0.25.0-ubuntu-x86_64` directory. Not only inconsistent, it's annoying af.

**Comment by sennui** [comment]
@sammy007 please check if you are not confused by some intermediary tools. OSX tends to create top level directory on its own. Our investigation revealed no console level differences. I checked both packages with `tar -xf`.

**Comment by sammy007** [comment]
I used `https://github.com/aeternity/epoch/releases/download/v0.25.0/epoch-0.25.0-osx-10.12.6.tar.gz`, unpacked it with `tax xzvf` on linux and osx and found no top level dir for it. It unpacks whole tree (bin, erts) to current directory.
