### ISSUE TITLE
Incorrect balance shown

### ISSUE THREAD

**Issue by kryztoval** [aeternity/epoch#1770]
## Expected Behavior
The balance should be correctly shown when asked via the rest interface
```
./aecli -u http://localhost:3013 -d http://localhost:3113 account balance wallet.ae
Enter the account password []:
<none>
  Balance ___________________________________________ 39999999999999994993
  Id ________________________________________________ ak_e8YApvLq9JyEWVg5KuyBo2gChWVwzD3g4oMHoVCSqg
7VpZsw7
  Nonce _____________________________________________ 4
</none>

```

## Actual Behavior
The balance gets rounded down
http://explorer.tld:3013/v2/accounts/ak_e8YApvLq9JyEWVg5KuyBo2gChWVwzD3g4oMHoVCSqg7VpZsw7
```
{
"balance": 39999999999999990000,
"id": "ak_e8YApvLq9JyEWVg5KuyBo2gChWVwzD3g4oMHoVCSqg7VpZsw7",
"nonce": 4
}
```

## Steps to Reproduce the Problem
Set up a small network, mine a few blocks, get a humoungous amount of balance, then check on the restful interface and via the sdk.
  
## Logs, error output, etc.
 No pertaining configuration needed

## Specifications
  - Virtualization: Docker
  - Node Version: 0.25.0

## Notes
I mined 4 blocks, at 10,000,000,000 AE per block. I registered 1 name and I spend 5000. the total should be  x4993 not x0000.

**Comment by hanssv** [comment]
Where did you see this rounding error, in the console? I know that (at least) Firefox does a poor job of presenting large numbers in json-terms!?

**Comment by kryztoval** [comment]
Based on your comment I went and verified the raw data. It seems the raw data does show the correct information. But the Aepp-blockchain-explorer does not.

So this must be a presentation error in the browser. I will check with the aepp-blockchain-explorer to see if there is a workaround about this.

![image](https://user-images.githubusercontent.com/5733028/48592547-7cf44f80-e90e-11e8-8613-fd7120618df5.png)
