### ISSUE TITLE
Fix Swagger code generation

### ISSUE THREAD

**Issue by wagerlabs** [aeternity/epoch#178]
- Fix Mustache templates.
- Submit patch upstream.
- Follow up on patch acceptance.

**Comment by uwiger** [comment]
I have run some separate experiments (after hours), generating erlang code for a fast dictionary based on the `swagger.yaml`. I pushed it provisionally to https://github.com/uwiger/swagger_erl_client

One idea was to efficiently validate input parameters in `aeu_requests:process_requests()`.
The official swagger codegen doesn't currently seem to have any support code for this.
