### ISSUE TITLE
how to connect to the mainnet

### ISSUE THREAD

**Issue by bitcodernull** [aeternity/epoch#1780]
## Expected Behavior

...

## Actual Behavior

...

## Steps to Reproduce the Problem

  1. ...
  1. ...
  1. ...
  
  
## Logs, error output, etc.
 
 (`epoch.yaml` configuration file, `log/epoch.log` log file plus other related logs, e.g., `log/epoch_sync.log`, `log/epoch_mining.log`; if it’s long, please paste to https://ghostbin.com/ and insert the link here)
 
 ...

## Specifications

  - Virtualization: [*none / metal / container / VM*]
  - Hardware specs: 
    * RAM: 
    * CPU:
  - OS: [*distribution, version*]
  - Node Version:

**Comment by hanssv** [comment]
Since the expected behavior matches the actual behavior I am not sure what is the issue?!

**Comment by bitcodernull** [comment]
aha :)

i have deployed the last release version, but i can not connect to the main net
it had not started to sync .

maybe i need to set the mainnet seed?

**Comment by jayphbee** [comment]
@bitcodernull  No mainnet yet.   I can keep sync up with 0.25.0, what's your configuration is and how do you start the node?

**Comment by bitcodernull** [comment]
the mainnet have not released now?
or i don't need to set seed?
 configure:

`sync:
    port: 3115
    external_port: 3015

keys:
    dir: keys
    password: "secret"

http:
    external:
        port: 20179
    internal:
        port: 30179

websocket:
    internal:
        port: 23114
    channel:
        port: 23014

mining:
    beneficiary: "ak_qRDNikCmCWMR4survdEXgD8pDy2fq1w3QKMunKZvdeMsWAHyV"
    autostart: false

chain:
    persist: true
    db_path: /mnt/aemain/aenode/node

fork_management:
    network_id: "ae_mainnet"
`

**Comment by bitcodernull** [comment]
i start node:

./bin/epoch start

**Comment by firephoenixer** [comment]
My system is ubuntu18.04.1 LTS. When i execute "bin/epoch start" , it allways report message below and failed. why?
2018-11-30 07:10:15 =CRASH REPORT====
  crasher:
    initial call: application_master:init/4
    pid: <0.1058.0>
    registered_name: []
    exception exit: {{{shutdown,{failed_to_start_child,exec,{bad_return_value,"Port program /home/aeminer001/tmp/node2/lib/erlexec-1.7.1/priv/x86_64-unknown-linux-gnu/exec-port with SUID bit set is not allowed to run without setting effective user!"}}},{exec_app,start,[normal,[]]}},[{application_master,init,4,[{file,"application_master.erl"},{line,134}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
    ancestors: [<0.1057.0>]
    message_queue_len: 1
    messages: [{'EXIT',<0.1059.0>,normal}]
    links: [<0.1057.0>,<0.958.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 610
    stack_size: 27
    reductions: 192
  neighbours:

**Comment by dincho** [comment]
@firephoenixer you try to run the node as root, which is not supported for security reasons. I know this ticket subject is clickbait, but please use separate tickets in future, thanks.

@bitcodernull There is [official 1.0.0 release](https://github.com/aeternity/epoch/releases/tag/v1.0.0) now, please download and try it, if you still having issues, I'd be glad to help.
