### ISSUE TITLE
Tree branch is incorrectly named v026

### ISSUE THREAD

**Issue by kryztoval** [aeternity/epoch#1785]
## Expected Behavior
All branches follow naming convention
v#.##.#

## Actual Behavior
This branch has no periods, commit date is Nov. 1st 2017
https://github.com/aeternity/epoch/tree/v026

## Steps to Reproduce the Problem
Go to git and look for the tags in aeternity/epoch  
  
## Logs, error output, etc.
None

## Specifications
Not needed

## Resolution
I am promoting the removal of the tag v026 or the renaming into the proper period format (which due to the date may very well be v0.2.6)

**Comment by hanssv** [comment]
Removed! Thanks for notifying us!

**Comment by kryztoval** [comment]
@hanssv No problem, I'll help anyway I can 👍
