### ISSUE TITLE
mean_miner.cu(356): warning: field initializers are a C++11 feature

### ISSUE THREAD

**Issue by Goffmann** [aeternity/epoch#1816]
ubuntu18.04
nvcc9.0
gcc5.5
g++5.5
0.25.0 epoch source code

when i make libblake2bso cudao30,there some warning:

nvcc -o cuda30 -DEDGEBITS=29 -arch sm_35 mean_miner.cu -L. -lblake2b
mean_miner.cu(356): warning: field initializers are a C++11 feature

mean_miner.cu(356): warning: field initializers are a C++11 feature

what should i do?

**Comment by jdgcs** [comment]
I compiled the new cuda30 solver  successfully with cuda10+gcc7.3(ubuntu18.04), it seems OK.

**Comment by jdgcs** [comment]
./cuda30 
GeForce GTX 1080 Ti with 10GB @ 352 bits x 5505MHz
Looking for 42-cycle on cuckoo30("",0) with 50% edges, 64*64 buckets, 176 trims, and 64 thread blocks.
Using 6976MB of global memory.
nonce 0 k0 k1 k2 k3 a34c6a2bdaa03a14 d736650ae53eee9e 9a22f05e3bffed5e b8d55478fa3a606d
Seeding completed in 41 + 31 ms
   2-cycle found
  30-cycle found
 754-cycle found
findcycles edges 63447 time 25 ms total 246 ms
0 total solutions

**Comment by Goffmann** [comment]
@jdgcs 

$ ./cuda30
P106-100 with 6080MB @ 192 bits x 4004MHz
Looking for 42-cycle on cuckoo30("",0) with 50% edges, 64*64 buckets, 176 trims, and 64 thread blocks.
GPUassert: out of memory mean_miner.cu 376

i compiled with cuda10+gcc7,and i got a new erro

**Comment by jdgcs** [comment]
@Goffmann 
Because "Using 6976MB of global memory" in my test, but there is only 6080MB memory in your card?

**Comment by Goffmann** [comment]
@jdgcs 
对，并且我解决这个问题了！嘻嘻

./cuda30 -s 会罗列一系列参数，其中一个是 -G ，有4/5/7三个，我的显卡显存6G，所以4/5可以正常运行，你的是7G。

我也想换大显存 *=*

**Comment by jdgcs** [comment]
@Goffmann 
老铁你好，这下就舒服多了，哈哈～加油！什么时候把多显卡的给搞了吧～

**Comment by jdgcs** [comment]
搞定就关了吧

**Comment by Goffmann** [comment]
@jdgcs 
同好同好。哈哈，总算是在蛛网deadline面前不紧张了。我就是买了个二手破矿卡随便玩玩，多显卡就交给矿老板着急去吧哈哈。

**Comment by jdgcs** [comment]
@Goffmann 
真爱粉，加了金刚狼的技术群没？
