### ISSUE TITLE
include loaded yaml file into crash.log

### ISSUE THREAD

**Issue by Zwilla** [aeternity/epoch#1817]
## Expected Behavior
wrong settings caused a crash
...

## Actual Behavior
crash
...

## Steps to Reproduce the Problem
use your own example:
https://github.com/aeternity/epoch/blob/master/apps/aeutils/test/data/epoch_full.yaml
## Logs, error output, etc.
 crash.log

##Why?
to identify which yaml was loaded
 
## Specifications
independent

**Comment by kryztoval** [comment]
Do you mean the location of the loaded yaml file or the actual configuration contents?

**Comment by Zwilla** [comment]
yes. And I know that if I open an other log file I can see the loaded config file.

Is there a way to set a fixed config file at bin/epoch start like

`bin/epoch start /home/user/ae/myconfig.yaml`

thx.

**Comment by kryztoval** [comment]
You can use any of those ways to define it,
https://github.com/aeternity/epoch/wiki/User-provided-configuration

I think what you want is
EPOCH_CONFIG=/home/user/ae/myconfig.yaml ./bin/epoch
