### ISSUE TITLE
RELEASE-NOTES-1.0.0-rc5 extract problem append config example

### ISSUE THREAD

**Issue by Zwilla** [aeternity/epoch#1847]
## Expected Behavior
`wget https://github.com/aeternity/epoch/releases/download/v1.0.0-rc4/epoch-1.0.0-rc5-ubuntu-x86_64.tar.gz`
`tar -xf epoch-1.0.0-rc5-ubuntu-x86_64.tar.gz`

has to extract into subfolder epoch-1.0.0-rc5 and not into current.
...

## Actual Behavior
extract into current folder

...

## Steps to Reproduce the Problem
see Expected Behavior
  
  
## Logs, error output, etc.
none
  ...

## Specifications
independent

**Comment by Zwilla** [comment]
crash happened only on upgrading from 0.25 to 1.0

**Comment by dincho** [comment]
Wrong dir it seems `v1.0.0-rc4`
