### ISSUE TITLE
Name claim won't accept ".aet" tld

### ISSUE THREAD

**Issue by kryztoval** [aeternity/epoch#1873]
It seems the name claim is not accepting .aet

**Comment by dincho** [comment]
Hello @kryztoval, [only `.test` is supported](https://github.com/aeternity/protocol/blob/epoch-v1.0.0/AENS.md#governance) right now.

**Comment by kryztoval** [comment]
But it is mainnet, not test net, why is this?

**Comment by dincho** [comment]
> But it is mainnet, not test net, why is this?
> My point is, why would it cost me real tokens to get a test name?

I'm sorry I cannot answer this, maybe @evdoks would know the reasoning behind that decision.

**Comment by evdoks** [comment]
@le-dawg Well, it is still a name and it can be used in production. Only `.test` namespaces are allowed for now to make sure that until we implement a fair pricing mechanism that will prevent name-squatting (e.g., an auction).

**Comment by kryztoval** [comment]
I don't know if this should be closed or not

**Comment by evdoks** [comment]
Closing as solved.
