### ISSUE TITLE
faild to start on  ethos

### ISSUE THREAD

**Issue by QQ40451** [aeternity/epoch#1885]
## Expected Behavior

start

## Logs, error output, etc.

11:16 下午 ethos@fae15d  [miner disallowed] /home/ethos/ae $ tail -f  log/erlang.log.1 
    stack_size: 27
    reductions: 213
2018-12-03 23:16:52 std_info            
    application: kernel
    exited: {{shutdown,{failed_to_start_child,kernel_safe_sup,{on_load_function_failed,rocksdb}}},{kernel,start,[normal,[]]}}
    type: permanent
{"Kernel pid terminated",application_controller,"{application_start_failure,kernel,{{shutdown,{failed_to_start_child,kernel_safe_sup,{on_load_function_failed,rocksdb}}},{kernel,start,[normal,[]]}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,kernel,{{shutdown,{failed_to_start_child,kernel_safe_sup,{on_load_function_failed,rocksdb}}},{kernel,start,[normal,[]]}}})

Crash dump is being written to: erl_crash.dump...done

**Comment by peterwillcn** [comment]
use ubuntu 18.04 is ok

**Comment by evdoks** [comment]
@QQ40451 Did it solve you problem?

**Comment by anysoft** [comment]
I meet the same issue.
I use the ubuntu-18.04.1.0-live-server-amd64.
Wget https://github.com/aeternity/epoch/releases/download/v1.0.1/epoch-1.0.1-ubuntu-x86_64.tar.gz
then i use tar command to extract files。
bin/epoch start 
the node can't start.(not a root user)

**Comment by anysoft** [comment]
and i can't see any logs
when i use root it can new the log

**Comment by dincho** [comment]
@anysoft If ever run it with root once, you should fix erlang pipes, see [my forum post](https://forum.aeternity.com/t/node-error-with-no-feedback/678/7?u=dincho)

**Comment by QQ40451** [comment]
> @QQ40451 Did it solve you problem?

I use koel_cuckoo  instead. 
discard solo.

**Comment by evdoks** [comment]
@anysoft Any specific error message? Did you create a config file as described [here](
https://github.com/aeternity/epoch/blob/master/docs/configuration.md#instructions)?

**Comment by dincho** [comment]
Hello, we don't officially support 14.04 see the [installation docs](https://github.com/aeternity/epoch/blob/master/docs/installation.md#retrieve-release-binary).

You may try to follow the build documentation (and adopt it to 14.04) and build the binaries yourself, however 14.04 builds are still not documented/supported.

(FYI 14.04 EOL is in 3-4 months)
