### ISSUE TITLE
The docs is  terrible

### ISSUE THREAD

**Issue by guotie** [aeternity/epoch#1926]
My team is develop a wallet, we want to support ae, but the docs is terrible.

How to get block? How to get transcation?

which url to call json-rpc?

How to register account?

where is the explorer?

**Comment by jayphbee** [comment]
You may need to have a look at this repo https://github.com/aeternity/protocol

**Comment by guotie** [comment]
I have read it！

**Comment by guotie** [comment]
got it!

**Comment by guotie** [comment]
http://aeternity.com/epoch-api-docs/?config=https://raw.githubusercontent.com/aeternity/epoch/master/apps/aehttp/priv/swagger.json#/external
