### ISSUE TITLE
how to export private key

### ISSUE THREAD

**Issue by guotie** [aeternity/epoch#1938]
How to export private key?

**Comment by dincho** [comment]
This is unclear to me
- where is your provide key stored now
- what format do you want your key to be exported to
- what's your expectation of the process

**Comment by guotie** [comment]
I use 
```
epoch keys_gen <password>
```
then, I got a pubkey, how to get the private key?

**Comment by evdoks** [comment]
@guotie Please, use the issue template to provide us with enough information to address the issue. For general questions on deployment, configuration and operation of the node, please use our [forum](https://forum.aeternity.com). Regarding your question, check [Beneficiary account](
https://github.com/aeternity/epoch/blob/master/docs/configuration.md#beneficiary-account). Make sure that you `epoch key_gen` **for testing purposes only**.

**Comment by guotie** [comment]
then, there is no way to export the private key like bitcoin in wif format?

**Comment by evdoks** [comment]
It is possible, but will require some code to be written. They private key is stored in `~/aeternity/node/generated_keys`, but right now there are no tools for exporting the key.
