### ISSUE TITLE
how to start testnet

### ISSUE THREAD

**Issue by guotie** [aeternity/epoch#1939]
how to start testnet?

**Comment by dincho** [comment]
Could you please be more specific? Do you want to start your own "testnet" or you want to join the testnet?

**Comment by guotie** [comment]
join the testnet

**Comment by evdoks** [comment]
@guotie Please, use the issue template to provide us with enough information to address the issue. For general questions on deployment, configuration and operation of the node, please use our [forum](https://forum.aeternity.com). Regarding your question, check [Configure an epoch node installed using a release binary](https://github.com/aeternity/epoch/blob/master/docs/configuration.md). Make sure that you specify correct `network_id` - see  [Network id](
https://github.com/aeternity/epoch/blob/master/docs/configuration.md#network-id) section of the document.
