### ISSUE TITLE
Blockchain Explorer does`nt work

### ISSUE THREAD

**Issue by prettyCoders** [aeternity/epoch#1984]

**Comment by jdgcs** [comment]
You can also check the block data here: https://www.aeknow.org/

**Comment by prettyCoders** [comment]
Thanks

**Comment by dincho** [comment]
Hi,
the explorer have its [own repository](https://github.com/aeternity/aepp-blockchain-explorer).
Also please follow the and fill-in the issues template in future.

Thanks.
