### ISSUE TITLE
Block data inconformity

### ISSUE THREAD

**Issue by prettyCoders** [aeternity/epoch#1985]
![image](https://user-images.githubusercontent.com/36216120/50532903-3aec3980-0b5b-11e9-9e59-b15f7b1b8f10.png)
![image](https://user-images.githubusercontent.com/36216120/50532910-4dff0980-0b5b-11e9-9adc-157155c417b6.png)
![image](https://user-images.githubusercontent.com/36216120/50532918-55beae00-0b5b-11e9-8548-a8e37fadf62f.png)
![image](https://user-images.githubusercontent.com/36216120/50532920-5c4d2580-0b5b-11e9-808a-0112d4cdb4ce.png)

**Comment by dincho** [comment]
Hi,
please fill-in the issue template so we can help eventually.

Thanks.
