### ISSUE TITLE
API request fails with 500 error

### ISSUE THREAD

**Issue by kryztoval** [aeternity/epoch#2003]
## Expected Behavior
Epoch node should respond to API requests if the parameters are correct

## Actual Behavior
Epoch node returns an Error 500

## Steps to Reproduce the Problem
Install an epoch node, and visit the api link directly

https://explorer.aepps.com/#/generation/15291
https://roma-net.aepps.com/v2/micro-blocks/hash/mh_txvtsx6ahZ7SEqCfL2K1ETuBzXrbdbjcQe3ZMJY2MczBm3mKv/transactions 
 
## Logs, error output, etc.
idk, this is your server

## Specifications
idk, this is your server

**Comment by hanssv** [comment]
That block contains a state channel transaction - this will be fixed in 1.2.0: https://github.com/aeternity/epoch/pull/1986

**Comment by kryztoval** [comment]
The merge you reference was done 7 days ago, if that already made it to the docker image d371a9b818b6 aeternity/epoch:master that was updated about 14 hours ago then i think it is still broken because  I just checked and it still returns error 500 Internal Server

**Comment by kryztoval** [comment]
I don't like this....
your node says this generation has no microblocks
https://roma-net.mdw.aepps.com/v2/generations/height/15291

but mine said there is one microblock
http://ae.criesca.net:3013/v2/generations/height/15291

I don't really care if your node is correct or not. What I do care is this:
The main idea of a blockchain is that the blockchain is the same in every single node. The fact that I am at a state where I see a transaction listed in a generation that other nodes in the network do not have is a really big problem. This is a trustless environment, and if the node can't decide or verify if it is complete or not then this network is not working at all.

**Comment by kryztoval** [comment]
The solution seems to be to upgrade the node and then delete the database.

If you are running a stand alone install the solution is to create a new node with the latest version, then let it sync over to the old one, and once it is done syncing it will have updated its database, you can now either use the new node ad delete the original node, or delete the original node's database and let it sync back.
