### ISSUE TITLE
Make it easier to test at the Erlang prompt

### ISSUE THREAD

**Issue by wagerlabs** [aeternity/epoch#205]
- Implement `ae:top`, `ae:balance`, etc.

**Comment by uwiger** [comment]
In the long run, I'd much prefer a CLI client interacting (e.g. via websockets) with the Erlang VM. The Erlang console is powerful, but a bit too powerful, and not very easy to make secure. Ideally, the CLI should make use of the swagger schema to simplify the maintenance of it.

**Comment by sennui** [comment]
we improved APIs to all services, so no need for this module. We can extract api layer from current controller and reuse it for HTTP and another protocols
