### ISSUE TITLE
Make it easy to quickly generate/restore a blockchain for testing

### ISSUE THREAD

**Issue by uwiger** [aeternity/epoch#207]
When testing e.g. sync or API logic, it would be extremely convenient to have either pre-mined blockchains saved on disk, or some method of quickly generating a realistic blockchain. Having to build one through slow mining for each test run will slow down CI dramatically.

I see a few options:
* Have a script, or similar, that mines some blocks and fakes some transactions, and then saves the chain to disk. This would need to be combined with a way to bootstrap the chain from disk. This would make it very easy to initialize a test that requires a chain to work with. A drawback is that one will test the same exact chain every time. Another drawback is that the chain will have to be rebuilt each time there are format changes.
* Build on the work needed for #113, e.g. making use of the [backup/restore feature](https://github.com/facebook/rocksdb/wiki/how-to-backup-rocksdb%3F) in Rocksdb
* Provide a way, at least for testing, to mine the chain much faster. This would make it possible to test more variations of blockchains for better test coverage.

**Comment by wagerlabs** [comment]
https://www.pivotaltracker.com/story/show/152475004
