### ISSUE TITLE
Let users generate a unique address whenever they want to receive tokens

### ISSUE THREAD

**Issue by wagerlabs** [aeternity/epoch#21]
We should be able to do with a single private key and multiple receive addresses. See [Hierarchical Deterministic keys using safe curves](https://crypto.stackexchange.com/questions/31369/hd-hierarchical-deterministic-keys-using-safe-curves)

**Comment by sennui** [comment]
The requested functionality is described in BIP-32 https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki

Couple good links:
https://bitcoinmagazine.com/articles/deterministic-wallets-advantages-flaw-1385450276/
https://www.cs.cornell.edu/~iddo/detwal.pdf

Known attack vector (possible to device master priv from master pub and couple child priv)
https://eprint.iacr.org/2014/998.pdf

**Comment by sennui** [comment]
Related work:

https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki

https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki

https://github.com/bitcoin/bips/blob/master/bip-0043.mediawiki

**Comment by wagerlabs** [comment]
Need a websockets API to create a new receive address. @sennui

**Comment by wagerlabs** [comment]
https://www.pivotaltracker.com/story/show/152471849
