### ISSUE TITLE
Application leaves epmd running after being stopped

### ISSUE THREAD

**Issue by deniskrishna** [aeternity/epoch#220]
After stopping the application via stop command `./bin/epoch stop` you can ensure that the epmd server is still running and listening on port 4369.
Here is *lsof* output:
```
lsof -i:4369
epmd    14937 garbage    3u  IPv4 0xbb373693973404d1      0t0  TCP *:4369 (LISTEN)
epmd    14937 garbage    4u  IPv6 0xbb3736939cadd279      0t0  TCP *:4369 (LISTEN)
```

here is *ps* output:
```
ps -A | grep -m1 epmd
14937 ??         0:00.00 /Users/garbage/osx-10.12.5-epoch-0.1.0/erts-9.0.5/bin/epmd -daemon
```

Should i manually kill the process or it must be deactivated automatically right after the
dependent services stopped?

Running this on OSX.

**Comment by sennui** [comment]
@deniskrishna Thanks for reporting this issue. The EPMD is higher level daemen (erlang port mapper daemon) started along Erlang VM. It can be shared between not related Erlang apps.

 We will surly cleanup after our selves when we deliver OS level start/stop scripts.

**Comment by evdoks** [comment]
We've created an [Pivotal Tracker issue](https://www.pivotaltracker.com/story/show/154175828) for this. Right now, if you are concerned about process isolation/cleanup, pleas use [docker](https://github.com/aeternity/epoch/blob/v0.5.0/docs/docker-testnet.md).
