### ISSUE TITLE
Rebuild state of the world when a stronger chain is found

### ISSUE THREAD

**Issue by wagerlabs** [aeternity/epoch#226]
We update the state of the world when the block is on the same chain. We need to update/rebuild when a _stronger_ chain is identified.

We are not going to identify common ancestors for the [Good Peers sprint](https://github.com/aeternity/epoch/milestone/3) but accept the stronger chain and rebuild from genesis.

**Comment by sennui** [comment]
copy-pasting comment from slack


Let's not go in this sprint into resolution where is the common ancestor. In case of stronger fork, lets accept the stronger chain and rebuild from genesis. To make it nicer, we need new api in state tree, that will wrap two existing apis: zero-out internal state  and after that build state from chain

zero out can be do with `force_trees`, and `apply_txs` will apply transactions from the new stronger fork
