### ISSUE TITLE
GHOST & DECOR+ consensus

### ISSUE THREAD

**Issue by wagerlabs** [aeternity/epoch#244]
There are potential issues with [SPECTRE](184) so we need to look at alternatives.

Ethereum uses the [GHOST consensus protocol](https://ethereum.stackexchange.com/questions/314/what-is-ghost-and-what-is-its-relationship-to-frontier-and-casper), as [described by Vitalik](https://blog.ethereum.org/2014/07/11/toward-a-12-second-block-time/), but [modifies it](https://github.com/ethereum/wiki/wiki/White-Paper#modified-ghost-implementation). 

Flaws [have been discovered](https://bitslog.wordpress.com/2016/04/28/uncle-mining-an-ethereum-consensus-protocol-flaw/) in the Ethereum implementation and [DECOR+](https://bitslog.wordpress.com/2014/05/07/decor-2/) has been proposed as the solution. The fix is an easy one and the author of the blog post notes that

> One of the solutions to the design problem in Ethereum is to replace uncle rewards by reward sharing, as specified by the [DECOR+ protocol](https://bitslog.wordpress.com/2014/05/02/decor/) described in this post. I’m preparing a paper on the DECOR+ protocol, and also the DECOR+ protocol has become one of the backbones of the [RSK smart contract platform](http://www.rootstock.io/).

Note that the flaws have nothing to do with the original description of the GHOST protocol, i.e. 

> In GHOST uncles have no other function and their transaction content is ignored. But Ethereum does more with uncles: uncles are paid a reward that is created from thin air specifically for that purpose.

GHOST has also been [analyzed from the security perspective](https://eprint.iacr.org/2016/545.pdf) and is easy to implement on top of our current Bitcoin consensus.

**Comment by kravets** [comment]
What are the potential issues with SPECRE ? 

(GHOST has both security flaws as showing in the SPECTRE literature as well as real pragmatic problems as used in Ethereum)

**Comment by uwiger** [comment]
@kravets a potential issue with SPECTRE would be what they hinted in the paper [(pg 11)](https://eprint.iacr.org/2016/1159.pdf):

```
Key to SPECTRE’s achievements is its willingness to delay the decision regarding
visibly double-spent transactions. It thus solves a weaker problem than traditional
consensus protocols. This fact also makes it less suitable for systems like Ethereum, 
where a total order over transactions is required.
```

At least tentatively, we don't think this needs to be an issue, but it needs to be fully understood.

**Comment by uwiger** [comment]
I haven't yet scrutinized DECOR+, but these are my tentative thoughts.

### SPECTRE and contract execution

The 'weakness' in SPECTRE is supposedly that it is not intended for systems requiring a total order, and the assumption is that e.g. ethereum requires this. But calling an ethereum contract (with a public result) is done through a `sendTransaction` (including paying some ether). If the output of the run is packed in a `'replyTransaction'`, which references the above `sendTransaction`, then a local order is established, and it should also be possible to ensure that the `replyTransaction` is not duplicated ("double-spent").

This would be similar e.g. to a client-server call in Erlang:

```erlang
call(Server, Req) ->
  Ref = make_ref(),
  Server ! {'$call', {self(), Ref}, Req},
  receive
    {Ref, Reply} -> Reply
  end.
```

SendTransactions could then in the general case also include hashes of other sendTransactions, establishing order where needed. But a total ordering is not attainable in distributed computing, and should not be a consensus requirement here.

Given this, SPECTRE does seem to be a good fit.

### GHOST, or DECOR+

My preliminary intuition is that these are "collision-detection" approaches where incentives are tuned for minimal disturbance. How the different variants compare differs partly based on how we expect attackers to behave - whether they are rational or irrational, profit-driven or simply want to mess things up. In contrast, SPECTRE describes a deterministic merge strategy which avoids collisions and is robust to brute-force attacks.

**Comment by kravets** [comment]
Ethereum and other "gas-ful" on chain Turing complete blockchains all suffer from the same fatal flaw called Verifier's Dilemma: 

https://www.reddit.com/r/ethereum/comments/3fcw0i/verifiers_dilemma_renders_ethereum_nonincentive/

Ultimately this and other issues arise do the the blockchain being "centralized for one block" i.e. The miner solving the next block has privileged knowledge of the future state of the chain that other miners don't.

If you guys are interesting in "crazy enough" solutions, I would suggest you take a look here

https://eprint.iacr.org/2016/871

What sets this research apart from IOTA and other DAG-like approaches is the PROOF of safety and liveness 

Cheers ...

**Comment by keypair** [comment]
postponed for now

**Comment by wagerlabs** [comment]
https://www.pivotaltracker.com/story/show/152474945
