### ISSUE TITLE
Clone github/testnet failed with 404 error

### ISSUE THREAD

**Issue by PaddySu** [aeternity/epoch#264]
Hi Joel,  I am intresting on AE and tried built mining box from my locla computer, but got failed while clone code from git hub, erorr was site not found https://github.com/aeternity/testnet.git], this was guide address https://blog.aeternity.com/æternity-testnet-install-and-mining-6f5b8e880ab1, thanks in advance.
 404 not found, this was error code

Any one did help about this ?

**Comment by sennui** [comment]
@PaddySu You tried fetching the initial version of AE chain. Please use epoch repo.
