### ISSUE TITLE
Implement Merkle trees

### ISSUE THREAD

**Issue by wagerlabs** [aeternity/epoch#29]
- Rewrite [this library](https://github.com/exthereum/merkle_patricia_tree) in Erlang.
- Add unit tests.

**Comment by lucafavatella** [comment]
I propose that implementation of Merkle tree in scope for this ticket:
* Aims at ability to store, lookup, compute root hash predictably by performing updates in a *specific* order;
* Does not aim at exhaustive documentation of internal structure;
* Does not aim at persistence.

I propose aiming at integrating https://github.com/KrzysiekJ/gb_merkle_trees

**Comment by wagerlabs** [comment]
Are we not storing Merkle trees in blocks? How are we not to aim at persistence then? 

If this is a stop-gap measure to unblock the rest of development then please suggest the _real_ solution. I understand that you have researched this extensively.

**Comment by sennui** [comment]
I think he meant the persistence inside the the tree. Because we do persist blocks, we can skip internal persistence

**Comment by wagerlabs** [comment]
@sennui @lucafavatella Then this is acceptable as the permanent solution.

**Comment by wagerlabs** [comment]
1. We are going to build the state of the world by processing the blockchain since genesis, just like Ethereum does it.
2. Light nodes will ask full nodes for proof of existence (proof of balance).
3. We will process transactions in the order they appear in the block.
