### ISSUE TITLE
aec_sync should not check whether or not to broadcast block

### ISSUE THREAD

**Issue by uwiger** [aeternity/epoch#298]
In the [handle_cast clause for `received_block`](https://github.com/aeternity/epoch/blob/master/apps/aecore/src/aec_sync.erl#L187), `aec_sync` checks whether the block exists on the chain; if it does, it doesn't broadcast.

While this is reasonable in principle, a check has already been done in [`aehttp_dispatch_ext`](https://github.com/aeternity/epoch/blob/master/apps/aehttp/src/aehttp_dispatch_ext.erl#L92). This function also calls `aec_sync` (asynchronously), then proceeds to write the block. The check in `aec_sync` is therefore redundant, but also introduces a race, where a block may erroneously not get re-broadcasted (at least by some nodes).

My suggestion: The check in `aec_sync` should be removed, and the API documented to clarify that `aec_sync` assumes that it's already been decided that the block/transaction should be broadcasted.

**Comment by happi** [comment]
The code in aehttp_dispatch_ext actually writes the block first and then calls aec_sync so even though this is done asynchronously I would suspect that almost no blocks would be re-broadcasted.
I agree with Ulf's suggestion: aec_sync:received_block should always re-send.
