### ISSUE TITLE
Peers utility - basic code

### ISSUE THREAD

**Issue by cytadela8** [aeternity/epoch#40]
Utility to talk with other peers.
I propose there should be a function for every request. This way we will limit typos in request names (to those functions) and we will be able to check the types of data provided to requests.
This depends on having any external API methods.

This issue contains only the basic code. No complex functions. Just functions common to all requests type and probably one request as an example of implementation.

**Comment by wagerlabs** [comment]
This task will be distributed among a bunch of others. We'll add functions to the _peer library_ as the need arises.

**Comment by cytadela8** [comment]
@wagerlabs As you think, but I consider implementing all non repetitive parts of the library a one day job.

**Comment by cytadela8** [comment]
Let's bring this issue back as this is my area of work. With this number I will implement a simple basic utility. Then for all requests types we can create separate issues.
