### ISSUE TITLE
Unable to load crypto library

### ISSUE THREAD

**Issue by qwertasa** [aeternity/epoch#417]
Unable to load crypto library. Failed with error:~n"~p, ~s"~nOpenSSL might not be installed on this system.~n
	load_failed
	"Failed to load NIF library /home/ae/0.3.1/lib/crypto-4.0/priv/lib/crypto: 'libcrypto.so.1.0.0: cannot open shared object file: No such file or directory'"

 dpkg -l | grep ssl | awk '{print $1, $2}'
ii erlang-ssl
ii flac
ii libcrypt-ssleay-perl
ii libevent-openssl-2.0-5:amd64
ii libflac8:amd64
ii libio-socket-ssl-perl
ii libnet-smtp-ssl-perl
ii libnet-ssleay-perl
ii libssl-dev:amd64
ii libssl-doc
ii libssl1.0.2:amd64
ii libssl1.1:amd64
ii libwavpack1:amd64
ii openssl
ii osslsigncode
ii perl-openssl-defaults:amd64
ii python-backports.ssl-match-hostname
ii python-nassl
ii python-openssl
ii python-passlib
ii ssl-cert
ii sslcaudit
ii ssldump
ii sslh
ii sslscan
ii sslsniff
ii sslsplit
ii sslstrip
ii sslyze
ii thc-ssl-dos
ii tlssled

**Comment by sennui** [comment]
more details please: Erlang/OTP ver, OS, how did you install Erlang, how do you build and run epoch?

**Comment by pckrell** [comment]
Isn´t this a huge security flaw?

**Comment by qwertasa** [comment]
Fixed via manually installation libssl-dev-1.0.0
