### ISSUE TITLE
Add RocksDB to the project skeleton

### ISSUE THREAD

**Issue by wagerlabs** [aeternity/epoch#42]

**Comment by lucafavatella** [comment]
From https://github.com/aeternity/epoch/issues/2#issuecomment-325902428 :
> We should use RocksDB instead via the [Erlang bindings](https://github.com/leo-project/erocksdb).

I see there are two RocksDB bindings on hex:
* https://hex.pm/packages/erocksdb i.e. https://github.com/leo-project/erocksdb
* https://hex.pm/packages/rocksdb i.e. https://gitlab.com/barrel-db/erlang-rocksdb

**Comment by lucafavatella** [comment]
I am writing here my state on this so far. Next steps are:
* Summarize differences in the two forks. Draft notes:
  * One seems more stable, the other one more feature rich for the sake of operations (e.g. backup, snapshot);
  * To be checked whether Erlang API is the same;
  * Identify kind of integration i.e. NF, dirty.
* Select one;
* Attempt inclusion in project. The two bindings have different build system (rebar vs. rebar3) so the other could be taken for easing integration.

---

> I see there are two RocksDB bindings on hex:
> * https://hex.pm/packages/erocksdb i.e. https://github.com/leo-project/erocksdb
> * https://hex.pm/packages/rocksdb i.e. https://gitlab.com/barrel-db/erlang-rocksdb

They diverged a year ago - see [1](https://github.com/leo-project/erocksdb/tree/e1c5f38) that is the same as [2](https://gitlab.com/barrel-db/erlang-rocksdb/tree/e1c5f38).

In the following is a summary of the differences:

| | [leo-project/erocksdb](https://github.com/leo-project/erocksdb/tree/e6dfa134d2262589b948ee4c7e959d99762638c1) | [barrel-db/erlang-rocksdb](https://gitlab.com/barrel-db/erlang-rocksdb/tree/047f2ba9128a9e3dc856f23e544226a523fd0f50) |
| --- | --- | --- |
| Build system | rebar | rebar3 |
| RocksDB version | 4.13.5 | 5.7.2 |
| Retrieval of C deps | Downloaded by [script](https://github.com/leo-project/erocksdb/blob/e6dfa134d2262589b948ee4c7e959d99762638c1/c_src/build_deps.sh#L62) called by rebar hook | Committed in the git repository itself |

**Comment by wagerlabs** [comment]
What do you recommend?

**Comment by lucafavatella** [comment]
I dropped this ticket having as state the work-in-progress branch https://github.com/aeternity/epoch/tree/gh-42-add-rocksdb-wip (a8247f3).

**Comment by lucafavatella** [comment]
> What do you recommend?

I expressed my recommendation, and motivations, in PR 57.
