### ISSUE TITLE
Serialize Merkle trees, blocks and headers for sending over the network

### ISSUE THREAD

**Issue by wagerlabs** [aeternity/epoch#45]
See #29 for the Merkle tree implementation.

- The serialization format should be easily parsed by JavaScript clients while being reasonably compact.

**Comment by wagerlabs** [comment]
Let's use JSON for now.

**Comment by cytadela8** [comment]
I think we can add a very nice JSON implementation with swagger. With help of swagger-codegen we might even be able to just pass our record to auto generated code as far as I remember swagger-codegen generated code mechanics.

**Comment by cytadela8** [comment]
Then in future we can create special endpoints for erlang clients with space efficient serialization.

**Comment by wagerlabs** [comment]
+1

**Comment by velzevur** [comment]
Transactions:

- [ ] Coinbase
- [ ]  Send
