### ISSUE TITLE
Mining less and less?

### ISSUE THREAD

**Issue by jdgcs** [aeternity/epoch#470]
> **curl -G http://127.0.0.1:3003/v1/account/balance --data-urlencode "pub_key=BFu61ms/GGg4czbXpNGoK8yzhIaFB0beDoGeOfwwBBzVa1URO2Y2W0EyYjdge97133ydjG5vlt8dylhWr2awMpc="** 

It showed that the balance was 650 test tokens about 6 hours ago, but about 1 hour ago, it became 490 tokens....Now, 480 tokens.

No other operations like token transfer.

Is that normal?

**Comment by gorillainduction** [comment]
See response in https://github.com/aeternity/epoch/issues/471
