### ISSUE TITLE
Lost mining balance

### ISSUE THREAD

**Issue by blue68** [aeternity/epoch#471]
Local deployment of a test node dug for some time through the private key to access the balance encountered the following questions:
1.post request can view 20;
Second request again to return a response: Account not found

<img width="515" alt="3c53cdfe-378d-4269-9cb0-445a7cbf708b" src="https://user-images.githubusercontent.com/2271067/33704938-55e568d8-db69-11e7-87c8-17e37a0d0dcc.png">

**Comment by blue68** [comment]
<img width="656" alt="2eea1da3-c945-489a-9a65-76ce5d487c41" src="https://user-images.githubusercontent.com/2271067/33705026-b2bb7598-db69-11e7-86d8-3ece4a28450e.png">

**Comment by jdgcs** [comment]
Same issue as your.

**Comment by gorillainduction** [comment]
Thanks for reporting this.

We found a pretty severe synchronization bug, and I will blame your situation on that for now ;-)

In the current test net release it is very easy to end up mining on a separate fork, and when the main fork eventually takes over, the account balance that you had in the losing fork will be gone.

We believe that we have fixed the sync issue, but if the problem persists after next release (scheduled for tomorrow) please ping this issue again.
