### ISSUE TITLE
Unable to process request for 'PostSpendTx'

### ISSUE THREAD

**Issue by jdgcs** [aeternity/epoch#487]
When I tried to send 0.01 test ae token to node2, 

curl -X POST -H "Content-Type: application/json" -d '{"recipient_pubkey":"BA8rCMut8z8if9YZd+1AIZAOuABkIL5ycSHbzNvQkQmtdDKaCHjnI0VKzhDOTTrW9s4d8ewX0Gas62GbpsJ7lhI=", "amount":0.01, "fee":1}' http://127.0.0.1:3113/v1/spend-tx

I got this: 

2017-12-09 23:12:16.981 [error] <0.6903.0> Unable to process request for 'PostSpendTx': {wrong_param,'SpendTx',schema,#{error => wrong_type,path => [<<"amount">>],schema => [{<<"type">>,<<"integer">>},{<<"format">>,<<"int64">>}],type => data_invalid}}

Sending the integer amount is OK.

**Comment by velzevur** [comment]
Hi @jdgcs ,
Thank you for yor comment. Epoch currently only accepts integers for spend transactions: both for the amount and for the fee. In the future a fractions could also be spend but then again - they'd be just integers of some other denomination.

**Comment by jdgcs** [comment]
thx!
