### ISSUE TITLE
the testnet version 0.3.5 uses more resources

### ISSUE THREAD

**Issue by xuanyu321** [aeternity/epoch#491]
It seems that the testnet version 0.3.5 uses more resources,even made my vmware crash,but it is normal in the version 0.3.3.And if I edit the mining parameter to false in the yaml configuration file,can't the aeternity get blocks from other nodes or sync blockchain?

**Comment by hanssv** [comment]
Version 0.3.5 change the default miner, from a less efficient less memory consuming miner to a more efficient, but more memory consuming miner. That could explain the change in resource usage?! (The miner can be configured in "releases/0.3.5/sys.config" - but that is not documented yet).

Setting `autostart` to `false` should not affect peer communication and block sync. If your node does not sync it could be one of several things: The configuration of peers is wrong, or your node is behind a firewall, or there is a problem in the node implementation. You could have a look in the log files and see if there are any errors visible there?! Especially interesting would be errors related to `ping` or `sync`.

**Comment by lucafavatella** [comment]
> It seems that the testnet version 0.3.5 uses more resources,even made my vmware crash,but it is normal in the version 0.3.3.

@xuanyu321 I believe that the issue you experienced is addressed in [release 0.4.1](https://github.com/aeternity/epoch/releases/tag/v0.4.1), that introduced the possibility for the user to configure a less memory-intensive (though usually slower) mining algorithm (i.e. the one that used to be the default one in version 0.3.3). Its release notes include  the instructions ([“Troubleshooting node failing mining attempts”](https://github.com/aeternity/epoch/blob/8e59d7a2d19811be7c47377274e329b7ca9501ec/RELEASE-NOTES.md#troubleshooting-node-failing-mining-attempts)).

**Comment by evdoks** [comment]
Closing as resolved
