### ISSUE TITLE
Will the testnet run on ARM devices?

### ISSUE THREAD

**Issue by iontom** [aeternity/epoch#504]
Before I spend time testing it out, I wanted to know if it runs on ARM? I have an nvidia jetson, but most people using ARM are Raspberry pie folks.

Cheers!

**Comment by hanssv** [comment]
I'm a Raspberry guy...

I’ve managed to compile and run the latest (Epoch 0.3.5)  version on a Raspberry Pi 3 - that is armv8 (64-bit) if I remember correctly. 

Installed Erlang from https://packages.erlang-solutions.com/erlang/esl-erlang/FLAVOUR_1_general/esl-erlang_20.1.7-1~raspbian~stretch_armhf.deb And then built the epoch node from source. The only thing that needed some tweaks was the PoW C++ code, it tried to use some advanced vector instructions, some non-existing compiler options and an include file that was missing, but it was pretty straightforward…

**Comment by vegabook** [comment]
So, I have a Jetson too. @hanssv by "Advanced Vector Extensions" do you mean using CUDA or some other method for taking advantage of the Jetson's GPU cores?

I want to mine on the Jetson too. Seems that the ethos of Aeternity, namely this pitch about even running on smartphones, means it should work on the TX2? Making full use of this dev board's hardware?

**Comment by stealth27374** [comment]
I'm interested in arm too,  need armhf so can run on my phone via Linux deploy app.

Installed Erlang and git and have it cloned.. How to build it? Can't find any instructions.

**Comment by wilsonk** [comment]
@vegabook The "Advanced Vector Extensions" are 256 bit AVX2 instructons, which are x86_64 specific instructions. Nothing to do with CUDA gpu code. There is also a version of the C++ PoW code that will run on NVIDIA gpu's though and it seems that it will also run on the Jetson gpu.

You can run the PoW code on older cpu's from Intel/AMD/ARM,  newer ones with AVX2 instructions, or gpu's that support CUDA...so there are options. The AVX2 version is many times faster than an ARM version would be and the CUDA version is slightly faster than the AVX2 one, I think.

**Comment by hanssv** [comment]
@stealth27374 The easiest is probably to do a `make prod-package` if successful that will give you a package that can be installed just like the released packages. Making is somewhat lengthy (will fetch a number of dependencies), but should be done within minutes rather than tens of minutes...)

**Comment by sennui** [comment]
I think all is clear here (Hans is part of core team). Its relatively easy to use Erlang VM on ARM. As for miner - the lean miner should avoid avx/sse, so you can try this insteam mean-miner
