### ISSUE TITLE
crypto:rand_uniform/2 is deprecated 

### ISSUE THREAD

**Issue by cytadela8** [aeternity/epoch#51]
crypto:rand_uniform/2 is deprecated and produces a warning. I think we should treat warning as errors. Is there some legitimate reason deprecated function has to be used? 

Code warning introduced by @akorosmezey, please comment on that.

Build log:
```
apps/aecore/src/pow_sha256.erl:111: Warning: crypto:rand_uniform/2 is deprecated and will be removed in a future release; use rand:uniform/1
```

**Comment by sennui** [comment]
what is the new function? @cytadela8 @akorosmezey ? Please refactor to get rid of the warning and use the new approach

**Comment by cytadela8** [comment]
@sennui I think we should also add a check to travis.

**Comment by cytadela8** [comment]
From crypto 4.0 release notes:
```Deprecate crypto:rand_uniform/2 as it is not cryptographically strong```

We should change to `rand:uniform`. For future production ready code we will need a cryptographically strong randomness in pow, but for tests anything randomish is good.
