### ISSUE TITLE
Account not found

### ISSUE THREAD

**Issue by mdix** [aeternity/epoch#543]
I started the node and am mining blocks. After I successfully mined a block:

```
2017-12-24 09:45:32.956 [info] <0.902.0>@aec_conductor:handle_mined_block:771 Block mined: Height = 755; Hash = 2a069a1fb3ddad0cfc23449df71ecc92340c8117779a3c7737dcf98160739cf7
```

I get my publickey (`curl http://127.0.0.1:3103/v1/account/pub-key`):

```
{"pub_key":"BJ6pfRowWYpogjpu6TDn2/hqjFcppo2yvWtJb1Z8DkGDZjMDPsbroHx4qfjePtBN+bKz8NnXH0Iwkz0a9G/vbg0="}%
```

and try to get my balance (`curl -G http://127.0.0.1:3003/v1/account/balance --data-urlencode "pub_key=BJ6pfRowWYpogjpu6TDn2/hqjFcppo2yvWtJb1Z8DkGDZjMDPsbroHx4qfjePtBN+bKz8NnXH0Iwkz0a9G/vbg0="`):

but I always get:
```
{"reason":"Account not found"}
```

Any help appreciated. Can also provide more logs if necessary.

**Comment by peter-fu** [comment]
Same here, however, after I had succesfully mined a block, I could see my balance instead of "account not found".

I guess it is still something which needs to be addressed, though.

**Comment by dincho** [comment]
@mdix could you please try the same workflow with latest version (0.6.0) ? Please note the API changes in v2, for details take a look in the [docs](https://github.com/aeternity/protocol/blob/master/epoch/api/account_api_usage.md)

**Comment by Zoesxw** [comment]
Hi, my node sees the same longest blockchain as the testnet. And it has run the whole night.  
But I use 'http://127.0.0.1:3103/v2/account/balance/...': it displays {"reason":"Account not found"}.
The epoch_mining.log always displays start mining but no block mined, sometimes error: 
'handle_worker_reply: 403 Got unsolicited worker reply' :
![image](https://user-images.githubusercontent.com/23716373/37069690-6feeabdc-21ef-11e8-9a39-151b24f0392b.png)
And the epoch_pow_cuckoo.log : 
![image](https://user-images.githubusercontent.com/23716373/37069765-cbdbda0a-21ef-11e8-80f8-dc8a49c4a9a3.png)
I follow the RELEASE-NOTES-0.8.0.  System:Ubuntu 16.04 LTS.

**Comment by dincho** [comment]
What I see from the provided (short) logs is that you didn't mined a block yet, if that is true - it's the reason you see "Account not found" error.

`handle_worker_reply: 403 Got unsolicited worker reply` is actually not an error, it means that your miner posted a solution but in the mean time the chain has been updated. @hanssv could you please confirm this explanation?

I created [PT ticket](https://www.pivotaltracker.com/story/show/155776152) to lower the priority.

**Comment by dincho** [comment]
I'm closing this ticket as this starts to become "catch all" for `{"reason":"Account not found"}` ambiguous error message.

If a public key has never been used in any transaction (includes coinbase) there is no account created for it yet in the state tree, thus the above error message.

**Comment by dincho** [comment]
Btw, this is already documented in https://github.com/aeternity/protocol/blob/epoch-v0.8.0/epoch/api/account_api_usage.md#retrieve-your-balance

**Comment by hanssv** [comment]
Confirm...
