### ISSUE TITLE
Have you guys even finished writing the whitepaper yet?

### ISSUE THREAD

**Issue by yanbosmu** [aeternity/epoch#562]
I found many "need cite" in it.
Can you just finish it?
Besides coding, whitepaper is also important

**Comment by knarz** [comment]
Hey, which whitepaper are you referring to? The `aeternity-reimagined` one? I agree that having a proper description of the system is important but getting all the parts specified has a higher priority right now. After that is done, the whitepaper will get an overhaul as well.

**Comment by evdoks** [comment]
There is also a number of specs in [protocol repo](https://github.com/aeternity/protocol), which describe the blockchain on a lower level. Most of the writing is happening there right now.
