### ISSUE TITLE
Question: Mining on testnet (epoch-0.4.1-osx-10.12.6); account balance went from +120 to 10

### ISSUE THREAD

**Issue by rodricios** [aeternity/epoch#580]
Is that expected behavior? I can provide more details if asked.

**Comment by mdix** [comment]
You should provide as much details as possible in a way as convenient as possible for the person who's looking at the issue in order to help him or her to answer your question / solve your problem. The more information you provide, the liklier you get help.

**Comment by sennui** [comment]
@rodricios Is it the same issue we talked over Slack? The reason back then was chain reset triggered by core  team.

**Comment by rodricios** [comment]
@sennui I haven't talked about this issue with anyone over slack. Unfortunately I do not have my environment setup to reproduce this issue so I will close this ticket for now.
