### ISSUE TITLE
Oracle no correct response?

### ISSUE THREAD

**Issue by jdgcs** [aeternity/epoch#599]
## Expected Behavior
According to the document(https://github.com/aeternity/protocol/blob/epoch-v0.5.0/epoch_api/oracle_api_usage.md), the last step of oracle response should be
`{"action":"new_oracle_response","origin":"node","payload":{"query_id":"oq$2fAZxtUdHtMk6cXjvk1GjMXMy2jDK2YEAmX174hohh3KcBtReL","response":"Hello, I am fine, thanks!"}}`

## Actual Behavior
But I got another query info:
`< {"action":"new_oracle_query","origin":"node","payload":{"sender":"ak$3qTmG1dtPVdZJhUAvpMFRr5YL1Jzaoak9BUPcCMf58HXJixH3rMvSK9PcSZQwqneaRTzibf9dqK5VuWvujvp25eLoeGzNZ","query":"How are you?","query_id":"oq$2fAZxtUdHtMk6cXjvk1GjMXMy2jDK2YEAmX174hohh3KcBtReL"}}`

## Steps to Reproduce the Problem

`>{"target":"oracle", "action":"register", "payload":{"type":"OracleRegisterTxObject", "vsn":1, "account":"ak$3qTmG1dtPVdZJhUAvpMFRr5YL1Jzaoak9BUPcCMf58HXJixH3rMvSK9PcSZQwqneaRTzibf9dqK5VuWvujvp25eLoeGzNZ", "query_format":"the query spec", "response_format":"the response spec", "query_fee":4, "ttl":{"type":"delta", "value":50}, "fee":5}}

<{"action":"register","origin":"oracle","payload":{"result":"ok","oracle_id":"ok$3qTmG1dtPVdZJhUAvpMFRr5YL1Jzaoak9BUPcCMf58HXJixH3rMvSK9PcSZQwqneaRTzibf9dqK5VuWvujvp25eLoeGzNZ"}}

< {"action":"mined_block","origin":"miner","payload":{"height":124,"hash":"bh$2wUKfTfJgxovHzp48pGBneuvpifuqAy5kXTABGkFA5Z5CNprVu"}}

> {"target":"oracle","action":"subscribe", "payload":{"type":"query","oracle_id":"ok$3qTmG1dtPVdZJhUAvpMFRr5YL1Jzaoak9BUPcCMf58HXJixH3rMvSK9PcSZQwqneaRTzibf9dqK5VuWvujvp25eLoeGzNZ"}}

< {"action":"subscribe","origin":"oracle","payload":{"result":"ok","subscribed_to":{"oracle_id":"ok$3qTmG1dtPVdZJhUAvpMFRr5YL1Jzaoak9BUPcCMf58HXJixH3rMvSK9PcSZQwqneaRTzibf9dqK5VuWvujvp25eLoeGzNZ","type":"query"}}}

>{"target":"oracle", "action":"query", "payload":{"type":"OracleQueryTxObject", "vsn":1, "oracle_pubkey":"ok$3qTmG1dtPVdZJhUAvpMFRr5YL1Jzaoak9BUPcCMf58HXJixH3rMvSK9PcSZQwqneaRTzibf9dqK5VuWvujvp25eLoeGzNZ", "query_fee":4, "query_ttl":{"type":"delta", "value":10}, "response_ttl":{"type":"delta", "value":10}, "fee":7, "query":"How are you?"}}

< {"action":"query","origin":"oracle","payload":{"result":"ok","query_id":"oq$2fAZxtUdHtMk6cXjvk1GjMXMy2jDK2YEAmX174hohh3KcBtReL"}}

< {"action":"mined_block","origin":"miner","payload":{"height":136,"hash":"bh$ikrKkGJFwcxzjLtRpU9KQRRWkCyEWi5iCqPeme9D3uT5qGLr6"}}

< {"action":"new_oracle_query","origin":"node","payload":{"sender":"ak$3qTmG1dtPVdZJhUAvpMFRr5YL1Jzaoak9BUPcCMf58HXJixH3rMvSK9PcSZQwqneaRTzibf9dqK5VuWvujvp25eLoeGzNZ","query":"How are you?","query_id":"oq$2fAZxtUdHtMk6cXjvk1GjMXMy2jDK2YEAmX174hohh3KcBtReL"}}

< {"action":"mined_block","origin":"miner","payload":{"height":144,"hash":"bh$VuivLtoNLhn36gyV3mhztDMfeRnayiNUznxLr47cBUBw2ey4n"}}

< {"action":"new_oracle_query","origin":"node","payload":{"sender":"ak$3qTmG1dtPVdZJhUAvpMFRr5YL1Jzaoak9BUPcCMf58HXJixH3rMvSK9PcSZQwqneaRTzibf9dqK5VuWvujvp25eLoeGzNZ","query":"How are you?","query_id":"oq$2fAZxtUdHtMk6cXjvk1GjMXMy2jDK2YEAmX174hohh3KcBtReL"}}

< {"action":"mined_block","origin":"miner","payload":{"height":145,"hash":"bh$2JECst2TPLfre9ptRHD3x7HE8TJ4SKc4Fv8X2SfU5sN75VSbhH"}}

>{"target":"oracle", "action":"response", "payload":{"type":"OracleResponseTxObject", "vsn":1, "query_id":"oq$2fAZxtUdHtMk6cXjvk1GjMXMy2jDK2YEAmX174hohh3KcBtReL", "fee":3, "response":"Hello, I am fine, thanks!"}}

< {"action":"response","origin":"oracle","payload":{"result":"ok","query_id":"oq$2fAZxtUdHtMk6cXjvk1GjMXMy2jDK2YEAmX174hohh3KcBtReL"}}

< {"action":"mined_block","origin":"miner","payload":{"height":153,"hash":"bh$2Ncck6dGdKrjvfciGcqffnWBFxBnVnq3aA1gBPvMb8sa2pGQ84"}}

< {"action":"new_oracle_query","origin":"node","payload":{"sender":"ak$3qTmG1dtPVdZJhUAvpMFRr5YL1Jzaoak9BUPcCMf58HXJixH3rMvSK9PcSZQwqneaRTzibf9dqK5VuWvujvp25eLoeGzNZ","query":"How are you?","query_id":"oq$2fAZxtUdHtMk6cXjvk1GjMXMy2jDK2YEAmX174hohh3KcBtReL"}}

< {"action":"mined_block","origin":"miner","payload":{"height":154,"hash":"bh$r8YxEggccxCz38zY1rFV9DKQau6wN3BJt8kev78nnMnU2qmgv"}}

< {"action":"mined_block","origin":"miner","payload":{"height":156,"hash":"bh$2iBPgjjrLqyCzFwVUhM7XUJJmSubP9byENC6QmvTWa94UM8Xzw"}}`
    
## Logs, error output, etc.
 
`[debug] <0.12167.3>@aec_tx:apply_on_state_trees:101 Tx {oracle_response_tx,<<4,233,19,167,30,165,213,223,27,49,92,69,238,58,5,145,208,209,147,10,54,15,127,140,245,102,63,88,127,211,114,191,198,54,24,247,160,117,250,22,69,178,148,69,159,228,71,253,177,141,248,186,214,139,2,8,70,5,46,96,247,209,7,96,205>>,3,<<218,90,181,121,90,152,203,187,168,41,151,51,246,164,177,171,101,100,87,39,240,19,215,189,191,236,202,96,147,86,209,187>>,<<"Hello, I am fine, thanks!">>,3} cannot be applied due to an error no_matching_oracle_query`

## Specifications

  - Virtualization: [*none / metal / container / VM*]
  - Hardware specs: 
    * RAM: 16G
    * CPU:XEON  E3-1230 V2
  - OS: Linux workstation 4.13.0-26-generic #29~16.04.2-Ubuntu SMP Tue Jan 9 22:00:44 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
  - Node Version:0.5.0

I'll re-test it later.

**Comment by hanssv** [comment]
The sequence of commands shows no evidence that you registered to get an event for responses to your query? But if that was just accidentally left out of the trace I think the reason why you do not get an event is that the query has expired? The query has a TTL of 10 blocks and is posted at block 136. The response seem to be posted at block 153?? Then the query is no longer there...

That said, it does look strange that you get the event for `new_oracle_query` multiple times, it looks almost as if the transaction is stuck in the mempool and gets posted again, and again...

If you can re-try the example with a bit longer TTL (both for the oracle just to be safe, and for the query). I'll try to replicate the problem locally as well!

**Comment by jdgcs** [comment]
Thanks for the reply, I'll try again.
