### ISSUE TITLE
Persist state of the world between node restarts

### ISSUE THREAD

**Issue by wagerlabs** [aeternity/epoch#61]
Each full node will rebuild the state of the world by processing the blockchain since the genesis block. This is a time-consuming operation so periodically saving the world to disk (RocksDB?) would be helpful. The node can restore the world after a restart and bring it up to update it based on the latest information received from peers.

**Comment by sennui** [comment]
We keep state of the world in internal (deserialized) block structure. We can leverage this and the mechanism for persisting blocks to persist state (before serializing we can extract trees and decorate the input to db)

**Comment by wagerlabs** [comment]
https://www.pivotaltracker.com/story/show/152471640
