### ISSUE TITLE
Broadcast transaction

### ISSUE THREAD

**Issue by wagerlabs** [aeternity/epoch#62]
- Check that the nonce of the transaction is the account nonce + 1.
- Sign the transaction and include the public key. Avoid the [transaction malleability](180) problem.
- Do not check the sender's account balance as it will be done when creating the block proposal.

**Comment by lucafavatella** [comment]
This ticket is meant to implement broadcast of transactions among peers, *including reception* of transactions.

Cc @uwiger @wagerlabs @sennui

**Comment by wagerlabs** [comment]
This ticket is about sending transactions out, not about receiving them. Please see description!

**Comment by wagerlabs** [comment]
https://www.pivotaltracker.com/story/show/152482324
