### ISSUE TITLE
How to build from source

### ISSUE THREAD

**Issue by ksallberg** [aeternity/epoch#684]
It seems that "make local-build" is the way to compile from source? Is there a reason the docs don't mention this? Can I create a PR and update the docs?

**Comment by dincho** [comment]
You should use ‘make prod-package’

**Comment by dincho** [comment]
Actually ‘make prod-build’ should work too, depending on what you’re trying to do.

Indeed we should document it.

**Comment by dincho** [comment]
Tracking as https://www.pivotaltracker.com/story/show/154919877

**Comment by sennui** [comment]
we need to extend Makefile docs. @ksallberg for now I can only advise going through Makefile targets to find relevant one. We will prioritize landing the better documentation

**Comment by ksallberg** [comment]
@sennui I am willing to improve the Makefile docs at least for the local-build, prod-build etc, and create a PR. That is kind of why I opened this ticket :) Would you appreciate that or should I contribute in some other way?
