### ISSUE TITLE
Service to hold blocks and headers in memory

### ISSUE THREAD

**Issue by wagerlabs** [aeternity/epoch#69]

**Comment by lucafavatella** [comment]
I had a chat with @sennui for clarifying scope of this ticket.

The service is one and is meant to keep:
* Two key-value storages:
  * Block headers - by block header hash;
  * Block - by block header hash. The block does not include the Merkle trees.
* The top - block header identifying the longest chain.

The service is meant to keep one chain.

State needs to be persisted in RocksDB.
Serialization/deserialization can be basic e.g. term_to_binary.

The service is meant to cover intake of new blocks/headers from sync/mining.

The service can be kept simple by enforcing assumption on inputs e.g.:
* Request to store block header returns error if previous block header unknown;
* Request to store block returns error if block header unknown.

The service is meant to cover swap of subset of top blocks for the ones from longer chain.

Open questions:
* Shall snapshots of state Merkle trees at each height be kept? If yes, where e.g. Merkle state service or chain service?

**Comment by lucafavatella** [comment]
For reference: [where previous documentation on node-local block-related structures used to be located](https://github.com/aeternity/testnet/wiki/Blocks#node-local-block-related-structures).

**Comment by lucafavatella** [comment]
For reference: chains in other blockchains:
https://github.com/bitcoin/bitcoin/blob/v0.14.2/src/chain.h
https://github.com/ethereum/go-ethereum/blob/v1.6.7/core/headerchain.go#L43-L47

**Comment by lucafavatella** [comment]
> ... how are we to find out the balance of an account at a given block height? We'll need this when processing blocks, I think.

@sennui I understand we agree the node keeps (we need to agree where) the state Merkle trees only for what the node considers to be the top/current block, so that the node can (1) mine on the top block and/or (2) produce proof of balance for an existing account at the top block.

@wagerlabs @sennui  I understand we do not identify the need to keep the balance of an account at arbitrary block height.

**Comment by wagerlabs** [comment]
How do we verify then that the transactions in a block we just received are valid?

We'll need to go through the transactions and verify that there was sufficient balance for a payment to happen, for example.

That said, if we receive the next block given our current block height then we can just check our state of the world. If we receive the block that's further out then we'll need to ask our peers to fill in the gap in the chain and update our state of the world using the missing blocks. Right?

Do we include the block height in the transaction structure? I think this is where things may become complicated. If the transaction is at the current height then we can validate now. If it's further out then we'll have to wait. What if it's as a lower block height, though?

**Comment by sennui** [comment]
I am not sure about including block height in transaction. It doesn't sound right.

Transaction is validate somewhere between mempool and mining. It is cross checked with balance of the state tree build as a new state tree (based on the lasterst state tree)

How to verify transaction in the middle of the blockchain? Well... one way is to trust that it was verified during adding it to the new block.

The other way is using proofs that I advice now to add to the blocks - yet another argument in favour of proofs @wagerlabs @zp-sd

**Comment by lucafavatella** [comment]
I confirm what @sennui wrote.

**Comment by wagerlabs** [comment]
We can't trust that transactions were verified by someone else. This is part of building consensus! 

I'll catch up on the proofs argument. 

This discussion seems to be related to the comments in #16.

**Comment by lucafavatella** [comment]
> For reference: chains in other blockchains:
> ...
> * Ethereum
>   * Section "10. Blocktree to Blockchain" in [yellow paper](http://yellowpaper.io/). Keyword: "total difficulty".
> ...
>   * [go-ethereum/core](https://godoc.org/github.com/ethereum/go-ethereum/core)

I am summarizing the outcome of my analysis below.

The [`BlockChain` class in Ethereum](https://godoc.org/github.com/ethereum/go-ethereum/core#BlockChain) fulfills lots of responsibilities:
* Storage of the blocktree i.e. the (potentially) multiple blockchains from genesis. It includes both tree of block headers without corresponding blocks, blocks, state;
* Block verification;
* Recomputation of "canonical chain" based on blocktree updates, based on "total difficulty";
* Storage of list of observed invalid/bad blocks.

I understand the scope of this ticket is smaller in order to keep it simple - see comments above e.g. aiming at one chain, not tracking difficulty, not tracking state.

**Comment by wagerlabs** [comment]
@lucafavatella The above doesn't tell me much. Why do I need to care what the `BlockChain` class does in Ethereum>

Please focus your comments on our implementation, e.g. let's do this and that and this is the benefit. I'm interested in how *we* should do it. I don't understand the benefit of what you wrote above and I won't unless I take the time to read and understand the Eth implementation. 

You took the time to read and understand the Eth and other implementations and should be able to make a decision on how we should move forward.

**Comment by lucafavatella** [comment]
> I am summarizing the outcome of my analysis below.
>
> The [`BlockChain` class in Ethereum](https://godoc.org/github.com/ethereum/go-ethereum/core#BlockChain) fulfills lots of responsibilities:

I should have been clearer. I meant that chain-like data structures in other implementations tend to merge in one class lots of responsibilities, while we are splitting them among distinct tickets and services. 

This ticket tracks storing one chain, and without state.

**Comment by wagerlabs** [comment]
What drawbacks do you see with our current approach?

How do you want to improve on it?

**Comment by sennui** [comment]
Mind that blockchain folk comes from cpp environment and very vertical architecture. Thanks to erlang we can go microservices (in one VM of course)

Indeed validation will go to #71 
State will go to State tree ticket 
New tree will go to Mempool ticket

So, I believe it will be better for us to keep it chopped in pieces, especially that the communication overhead is minimal.

**Comment by lucafavatella** [comment]
> What drawbacks do you see with our current approach?
>
> How do you want to improve on it?

Adding to the comment by @sennui:

Keeping one chain only requires the decision to follow an alternative fork to be taken by the “sync” portion of code - external to the blocks/headers chain service tracked in this ticket. After having developed this iteration of “blocks/headers chain service” (tracked in this ticket) and the first iteration of the sync code, we will be in a position to decide whether the “blocks/headers chain service” shall track multiple chains. @sennui comments?

Similarly for whether to consider “total difficulty” of a chain (i.e. sum of difficulty of all block headers up to genesis) on which chain to follow in presence of forks. This is related to consensus among forks, I am not sure which ticket is meant to track this - @sennui do you know?

On storage of list of observed invalid/bad blocks, that is an optimization and I commented in another ticket https://github.com/aeternity/epoch/issues/71#issuecomment-327768862 .

**Comment by sennui** [comment]
I wonder if we can implement now the positive path and think about fork handling just a bit later?

We will have clearer distinction between services? cc: @wagerlabs 

You are right, we should consider total difficulty from the genesis, when deciding on fork handling.

I would like to keep *sync* network and gossip oriented. Sync will hand-off blocks to #71. And your service #69 will be responsible to potentially track and compute 2nd chain difficulty. I am open to suggestions, but this architecture is pretty clear for me.

CC: @cytadela8 @akorosmezey (adding akos in cc, because he will help Artur with the incoming-block area)

**Comment by lucafavatella** [comment]
The PR #92 implemented in-memory chain service tracking one chain, without the state trees:
* The service lacks support for changing tracked chain / fork, i.e. the service can only track a chain that grows one header at a time on the top;
* The service has no persistence;
* The service does not consider difficulty.

@sennui Can this be closed, and track the rest in other tickets?

**Comment by lucafavatella** [comment]
I am unassigning myself from this ticket as I am working on #109.
