### ISSUE TITLE
Oracle API is not responding on subscriptions

### ISSUE THREAD

**Issue by tillkolter** [aeternity/epoch#710]
## Expected Behavior

```
{
    "action":"subscribe",
    "origin":"chain",
    "payload": {
        "result":"ok",
        "subscribed_to: {"oracle_id":"ok$3jzZyCLFtHVD7yVdEhGJFM3LjeXrKqWxnHbCYzhnrrR4DkdFtaJuxQvrR8VbbXExDPkCHFAei5q969JA6EayQpb8z5C3Mf","type":"query"}
}}
```

## Actual Behavior

No Response

## Steps to Reproduce the Problem

  1. 
Send
```
{
 "target": "chain",
 "action": "subscribe",
 "payload": {
  "type": "query",
  "oracle_id": "ok$3XpVuN8nVHmgSCtZGXtpzkiS2DufNDjWs9PdY2wxhDtMfeAGfJp8GfDMhH7rou2B2RVWcNhQtrVFNsRdvDsecsrLYHyuA2"
 }
}
```
  
## Logs, error output, etc.
 
Nothing relevant in the logs.

## Specifications

  - Virtualization: none
  - Hardware specs: 
    * RAM: < 20GB
    * CPU: 64-bit 8 Core Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz
  - OS: Debian Jessie
  - Node Version: d254ee9bc0966a37251a30bb078e0e6d3d9628fd

**Comment by hanssv** [comment]
Code works just fine, but the documentation is bad... The examples in https://github.com/aeternity/protocol/blob/master/epoch/api/oracle_ws_api.md are not properly updated. It should be `"type": "oracle_query"`

A PR for the documentation is here https://github.com/aeternity/protocol/pull/49
