### ISSUE TITLE
Please help Chinese investors re-get tokens.

### ISSUE THREAD

**Issue by jdgcs** [aeternity/epoch#78]
Hi, dear AE team,

I am an investor from China, and I invested AE on ico365.com .

As you known, China banned ICO.

If ico365.com send AE coins to us directly, they will be in jail mostly.

So an option is ico365 sending AE coins and user lists to AE foundation, and AE foundation send AE coins to the investors.

I believe this is the best solution for AE foundation, ico365.com and the investors.

I kown, it's really bothering you team. It's hard in China now...but we love AE.

Regards,

Liu Yang

**Comment by wagerlabs** [comment]
Please contact Marion, Vlad or Nas on Slack or Telegram.
