### ISSUE TITLE
Token distribution issues for China

### ISSUE THREAD

**Issue by zcc0721** [aeternity/epoch#79]
Dear AE team,

I am a AE contributor from China. I have been actively involved in your project during the past few months through ICO365(https://www.ico365.com/). We believe AE is a world-changing project.

However, due to the impact of Chinese new policy, we could not obtain the AE token from ICO365. We have communicated with ICO365 and were advised that we should contact directly with you. We sincerely support AE project and hope we can obtain our AE token immediately.

We hope that you can protect our interest and do not return ETH to us since the time cost is huge!

Please find below our advice:

1. Please help urge the ICO365 to distribute the AE token to us ASAP.
2. If 365 declined the request, we hope AE team could consider giving us a chance to re-contribution.

Thank you!

**Comment by wagerlabs** [comment]
Not related to blockchain development. Do not post ICO and token issues here!

**Comment by wagerlabs** [comment]
Please get in touch with the AE team on Slack or Telegram.
