### ISSUE TITLE
The book of blood and tears

### ISSUE THREAD

**Issue by CockyCat** [aeternity/epoch#85]
Hi AE Team，
We are AE investors from China who have invested in the AE project through the ico365 platform!

After a long wait, we finally ushered in the AE issuing day, ganqiao meets Chinese block chain project financing risk token policies, believe you also know, AE tokens issued encountered twists and turns! But we're all looking for the best solution!

We are a loyal supporter of AE, very optimistic about the future of AE, very optimistic about your current core team! So all the Chinese AE investors are not required to return (ETH, we also know that the ETH part of the AE investment is stolen, but you still protect the interests of investors issued tokens, although this is what you should do, we still admire your moral integrity.) We all insist on AE tokens!

At present, the government Chinese out regulatory policy is mainly for the ICO platform, all tokens may not be issued, and discuss the project investment, in line with the principle of voluntary, intermediary platform ico365 will serve you free currency exchange!
Because you have announced that you insist on non refundable currencies, but ico365 is afraid to send money in the face of national policy, and 365 said that it will operate according to the announcement of your project party!

So now you suggest a "voluntary return tokens" announcement, you know that if you say so, a large number of investors returned to AE, and you have not get so much eth to investors, on behalf of all Chinese investors to tell you the truth, you do not worry, because they did not request a refund eth, we are going to ae! But, you must issue the "voluntary return tokens" before the official announcement, ico365 with Chinese government cross, do the work in accordance with the token repaying a voluntary project and investor agreement! Such a plan is in line with China's policy, and can skillfully solve the current problems of all parties, do you think?

All Chinese AE investors
2017-09-07

**Comment by wagerlabs** [comment]
Please get in touch with Marion and Vlad on Slack or Telegram. This is a blockchain development area that has nothing to do with tokens!

**Comment by AegisDu** [comment]
he just wanna to get his right,and benifit,pls understand
